
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Azzam
 */

public class MainProgram extends javax.swing.JFrame {

    /**
     * Creates new form MainProgram
     */
    
    class penghitung{
        double usdtoother(double a, double b){
            double hasil = a*b;
            return hasil;
        }
        double othertousd(double a, double b){
            double hasil =a/b;
            return hasil;            
        }
    }
    
    
    
    
    public MainProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        inputamount = new javax.swing.JTextField();
        pil1 = new javax.swing.JComboBox<>();
        pil2 = new javax.swing.JComboBox<>();
        convert = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Input Amount");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 20));

        inputamount.setBackground(new java.awt.Color(68, 68, 68));
        inputamount.setForeground(new java.awt.Color(255, 255, 255));
        inputamount.setBorder(null);
        inputamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputamountActionPerformed(evt);
            }
        });
        jPanel1.add(inputamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 208, 37));

        pil1.setBackground(new java.awt.Color(204, 204, 204));
        pil1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "IDR", "SGD", "SAR", "JPY" }));
        pil1.setBorder(null);
        pil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil1ActionPerformed(evt);
            }
        });
        jPanel1.add(pil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        pil2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "IDR", "SGD", "SAR", "JPY" }));
        pil2.setSelectedIndex(1);
        pil2.setBorder(null);
        pil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil2ActionPerformed(evt);
            }
        });
        jPanel1.add(pil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        convert.setIcon(new javax.swing.ImageIcon("F:\\program\\praktikum dkp\\TA\\Converter\\Repeat Grid 7.png")); // NOI18N
        convert.setBorder(null);
        convert.setBorderPainted(false);
        convert.setContentAreaFilled(false);
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        jPanel1.add(convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, 50));

        output.setForeground(new java.awt.Color(68, 68, 68));
        output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        output.setText("-");
        jPanel1.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 220, 36));

        jPanel2.setBackground(new java.awt.Color(0, 209, 205));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Converter");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 209, 205));
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\program\\praktikum dkp\\TA\\Converter\\Repeat Grid 2.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 50));

        jButton2.setBackground(new java.awt.Color(0, 209, 205));
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\program\\praktikum dkp\\TA\\Converter\\Repeat Grid 5.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("From");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("To");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("F:\\program\\praktikum dkp\\TA\\Converter\\Group 2.png")); // NOI18N
        jButton3.setActionCommand("clear");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pil1ActionPerformed

    private void pil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pil2ActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        output.setForeground(Color.white);
        
        double input,hasil,a;
        double uang[]= {1, 14915, 1.413, 3.757, 106.942};
        String matauang[]= {"$","Rp","$","ر.س","¥"}; 
        penghitung hitung = new penghitung();
        //DecimalFormat numberFormat = new DecimalFormat("#.00");
        DecimalFormat numberFormat = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols format = new DecimalFormatSymbols();
        format.setCurrencySymbol(matauang[pil2.getSelectedIndex()]);
        format.setMonetaryDecimalSeparator(',');
        format.setGroupingSeparator('.');
        
        numberFormat.setDecimalFormatSymbols(format);
        
        input = Double.parseDouble(inputamount.getText());
        if(pil1.getSelectedItem().equals("USD")){
            hasil = hitung.usdtoother(input, uang[pil2.getSelectedIndex()] );            
            output.setText(numberFormat.format(hasil));
            
        }
        else{
            a = hitung.othertousd(input, uang[pil1.getSelectedIndex()] );            
            hasil = hitung.usdtoother(a, uang[pil2.getSelectedIndex()]);
            output.setText(numberFormat.format(hasil));
         
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_convertActionPerformed

    private void inputamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputamountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputamountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         setState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        inputamount.setText(" ");
        output.setText(" ");
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JTextField inputamount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel output;
    private javax.swing.JComboBox<String> pil1;
    private javax.swing.JComboBox<String> pil2;
    // End of variables declaration//GEN-END:variables
}
